version: "3.5"

services:

  nginx:
    image: nginx:latest
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./app:/var/www/html
    - ./configs/nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx#
#services:
#  nginx:
#    image: 'bitnami/nginx:latest'
#    depends_on:
#      - phpfpm
#    networks:
#      - app-tier
#    ports:
#      - 127.0.0.1:80:80
#      - 443:443
#    volumes:
#    - ./app:/var/www/html
#    - ./configs/nginx:/etc/nginx/conf.d
#    - ./logs/nginx:/var/log/nginx#
#
  php-fpm:
    build:
      context: php-fpm
    volumes:
    - ./app:/var/www/html

  mardiadb:
    image: mariadb:10.4
    ports:
    - 127.0.0.1:3306:3306
    env_file: .env
    environment:
    - MYSQL_ROOT_PASSWORD:$MYSQL_ROOT_PASSWORD
    volumes:
    - ./databases/mariadb:/var/lib/mysql