apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: maria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.4
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_USER
          valueFrom:
           secretKeyRef:
            name: maria-secret
            key: maria-user
        - name: MARIADB_PASSWORD
          valueFrom:
           secretKeyRef:
            name: maria-secret
            key: maria-password
---
apiVersion: v1
kind: Service
metadata:
  name: maria-service
spec:
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306